# Generated by Django 6.0.3 on 2026-06-14 04:12

from django.db import migrations, models


def clear_default_avatars(apps, schema_editor):
    """Existing rows store the literal 'default.jpg' (a file that never existed),
    which would render as a broken image. Blank them so the initial-letter
    fallback shows instead."""
    Profile = apps.get_model('users', 'Profile')
    Profile.objects.filter(profile_picture='default.jpg').update(profile_picture='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.RunPython(clear_default_avatars, migrations.RunPython.noop),
    ]
