# Generated by Django 6.0.3 on 2026-06-05 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clip_converted_video_file_alter_clip_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clip',
            options={'ordering': ['-date_uploaded']},
        ),
        migrations.AddField(
            model_name='clip',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='clip',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['-date_uploaded'], name='clips_clip_date_up_04d050_idx'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['uploader', '-date_uploaded'], name='clips_clip_uploade_03f898_idx'),
        ),
    ]
