# Generated by Django 6.0.3 on 2026-06-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_backfill_ready_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='clips/thumbnails'),
        ),
    ]
