# Generated by Django 6.0.3 on 2026-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_clip_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
