# Generated by Django 6.0.3 on 2026-06-16 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_alter_clip_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('UNLISTED', 'Unlisted')], default='PUBLIC', max_length=10),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['visibility', '-date_uploaded'], name='clips_clip_visibil_bb1821_idx'),
        ),
    ]
